cache:
  mount:
    - /drone/pip-cache
build:
  wheels:
    image: fusionapp/base
    pull: true
    environment:
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PIP_CACHE_DIR=/drone/pip-cache
    commands:
      - /appenv/bin/pip install --requirement requirements.txt .
      - /appenv/bin/trial fusion_index
publish:
  docker:
    registry: scarlet.fusionapp.com:5001
    mirror: https://scarlet.fusionapp.com:5002
    insecure: false
    repo: fusionapp/fusion-index
    tag: $$BRANCH
    when:
      branch: [master]
deploy:
  rancher:
    url: https://rancher.fusionapp.com
    access_key: $$RANCHER_PRODUCTION_ACCESS_KEY
    secret_key: $$RANCHER_PRODUCTION_SECRET_KEY
    service: fusion-index/fusion-index
    docker_image: scarlet.fusionapp.com:5000/fusionapp/fusion-index:master
    start_first: false
    when:
      event: push
      branch: [master]
notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: general
    username: drone
notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: production
    username: drone
    when:
      event: push
      branch: [master]
branches:
  - master
