pipeline:
  restore_cache:
    image: appleboy/drone-sftp-cache
    server: sftp-cache.drone7.non-production.fusionapp.com
    port: 45945
    username: drone-cache
    path: /drone-cache
    restore: true
    ignore_branch: true
    mount:
      - /drone/pip-cache
    secrets:
      - sftp_cache_password
  build:
    image: fusionapp/base
    pull: true
    environment:
      - PIP_CACHE_DIR=/drone/pip-cache
    commands:
      - mkdir -p $PIP_CACHE_DIR
      - /appenv/bin/pip install --requirement requirements.txt .
      - /appenv/bin/trial fusion_index
  rebuild_cache:
    image: appleboy/drone-sftp-cache
    server: sftp-cache.drone7.non-production.fusionapp.com
    port: 45945
    username: drone-cache
    path: /drone-cache
    rebuild: true
    ignore_branch: true
    mount:
      - /drone/pip-cache
    when:
      event: push
      branch: master
    secrets:
      - sftp_cache_password
  publish:
    image: plugins/docker
    repo: eu.gcr.io/fusion-168903/fusion-index
    tags: ${DRONE_BRANCH}
    registry: eu.gcr.io
    mirror: https://eu-mirror.gcr.io
    username: _json_key
    when:
      event: push
      branch: master
    secrets:
      - docker_password
  deploy:
    image: peloton/drone-rancher
    url: https://rancher.fusionapp.com
    service: Fusion/fusion-index
    docker_image: eu.gcr.io/fusion-168903/fusion-index:${DRONE_BRANCH}
    start_first: false
    confirm: true
    timeout: 120
    when:
      event: push
      branch: master
    secrets:
      - rancher_access_key
      - rancher_secret_key
  slack:
    image: plugins/slack
    secrets:
      - slack_webhook
    when:
      status:
        - success
        - failure
branches:
  - master
  - staging
  - trying
