sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
branches:
  only:
  - master
matrix:
  include:
    - env: TOXENV=py27
    - env: TOXENV=pypy
install:
- pip install -U pip setuptools wheel
- pip install tox codecov
- |
  if [ "${TOXENV}" == "pypy" ]; then
    git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
    PYENV_ROOT="$HOME/.pyenv"
    PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv install pypy-5.8.0
    pyenv global pypy-5.8.0
  fi
script:
- tox
after_success:
- codecov
notifications:
  email: false
  slack:
    secure: X/l1d5DKxbdnlaaNipyVXX4h9KwfG71OjFp0bdkq65HWRUDoU6uboF+jropDPDt0weK5rMMRG3zRkQnJB783EGVM7phy/odVwMBHoxrIMQBKk8hTZ3RiFXJfhqT4PlRTiPZGhbys2UGMjSJtIa1lkDQh6CUDt+UqXlgunSKtFj7JZmyjguXQ9UVmOZlYLDVgToyda9vDUvfC/gcBBALUAivNb9OoLVxlIsFB8xoPSzMQsE5ukWlFPAAN3UiG301qlACLFL2AiJkzPm4Pqg/9uUs/frWAsasa/trEKHKcJ3pFA1LGN555+QMpmWbcqwfcDy5Dh9Vb4+4ADRdTiCYoGbw52lVeH3yYOIoeLRP54PMULCRsbRmW6U3CngqaBceILjNI1hQZLasvNIyKL5QSj2n0m+l5CMGKnawdPl75DQQd/4YlldpkkKKhW13ee4ckbVSy6LY8M7xweIEZatZFbnnlLSrajHtDWZbL0Vh4nYl/sberEZHUqxvQDOWeCDpUS6TVexQTlO/CvdyC6gFlsd5TwA1OdsZe9GdcrKjcNW4rq5QkOdphAiniqk8KJnuwPsUThzt5orrs10CwT2oAJWtNOjRY4JGpbLOay2VD5hwlj5xxV5suFLsir29/16/FFTtn9c9/J2aMsflVYGzsBN9wRrz8im5RpoEqX/qyhUs=
